const ON_LOADING = 'BLOG_ON_LOADING';
const UPDATE_LIST = 'BLOG_UPDATE_LIST';
const UPDATE_ITEM = 'BLOG_UPDATE_ITEM';
const ADD_ITEM = 'BLOG_ADD_ITEM';

export {
    ON_LOADING,
    UPDATE_LIST,
    UPDATE_ITEM,
    ADD_ITEM
};
